In [1]:
import numpy as np

## Numpy array

In [4]:
# 1D array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
# 2D array
arr = np.array([[1,2], [4,5]])
arr

array([[1, 2],
       [4, 5]])

In [7]:
arr.shape

(2, 2)

In [15]:
# indexing
print(arr[0]) # get row 0
print(arr[1]) # get row 1
print(arr[1, 1]) # get single element first value is for row and second for column
print(arr[1][1]) # get single element in another way

[1 2]
[4 5]
5
2


## Different ways of creating arrays

In [17]:
# create an array of all zeros
np.zeros((3,4)) # first value of tuple argument is for number of rows and second for column

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#Create an array for all ones
np.ones((3,4)) # first value of tuple argument is for number of rows and second is for column

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.full((3,4), 7) 
# first argument i.e tuple is for array size and 
#second argument is for the value of elment it will have

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [23]:
#create Identity matrix
np.eye(3) # 3X3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#create a matrix with random values
np.random.random((2,3))

array([[0.37065833, 0.81567944, 0.08937789],
       [0.61670743, 0.52256284, 0.76512497]])

## Datatype

In [25]:
arr = np.array([2,3,4,5])

In [26]:
arr.dtype

dtype('int64')

In [27]:
arr = np.array([2., 3., 4.])

In [28]:
arr.dtype

dtype('float64')

## Array math in numpy

In [29]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [33]:
#Element wise sum. Both prodive same array
print("------------SUM-------------------")
print(x + y)
print(np.add(x, y))
print("----------------------------------")
#Element wise subtraction. Both prodive same array
print("------------SUBTRACT--------------")
print(x - y)
print(np.subtract(x, y))
print("----------------------------------")
#Element wise multiplication. Both prodive same array
print("------------MULTIPLY--------------")
print(x * y)
print(np.multiply(x, y))
print("----------------------------------")
#Element wise division. Both prodive same array
print("--------------DIVIDE--------------")
print(x / y)
print(np.divide(x, y))
print("----------------------------------")
#Element wise square root. Returns array
print("------------SQUARE ROOT--------------")
print(np.sqrt(x))
print("----------------------------------")

------------SUM-------------------
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
----------------------------------
------------SUBTRACT--------------
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
----------------------------------
------------MULTIPLY--------------
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
----------------------------------
--------------DIVIDE--------------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
----------------------------------
------------SQUARE ROOT--------------
[[1.         1.41421356]
 [1.73205081 2.        ]]
----------------------------------


###### Note: * notation is for elementwise multiplication not for matrix multiplication

## Matrix multiplication

In [37]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
print()


# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print()

# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

219
219

[29 67]
[29 67]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


## Sum function in numpy

In [38]:
x = np.array([[1,2],[3,4]])

In [42]:
# returns the sum of all element in array/matrix
print(x.sum())
print(np.sum(x))

10
10


In [45]:
# returns the sum of each row
print(np.sum(x, axis=0))
# returns the sum of each column
print(np.sum(x, axis=1))

[4 6]
[3 7]


## Transpose of matrix

In [46]:
x.T

array([[1, 3],
       [2, 4]])